### PR TITLE
PDU products from Cyber Power Systems

### PR DESCRIPTION
**Pull request by gwythaint**

### CODE REVIEW

**Comment by bene42** [comment]
Hi,
thanks for the patch.

There are two minor issues:
1. I did not wrote *your* code and I do not adorn myself with borrowed plumes:
Please update the copyright section and add your  "Signed-off-by: Tag" to the commit. 
2. Please add a short commit message and state the origin of the MIB file.

Regards
    Benedikt Spranger

**Comment by bgermann** [comment]
A Signed-off-by on r4d has the same semantics as for the Linux kernel: https://developercertificate.org/

**Comment by bgermann** [comment]
What is the license of the provided CPSMIB2019.mib?

**Comment by gwythaint** [comment]
Good question. CyberPower isn't very descriptive about it. 
https://www.cyberpowersystems.com/product/software/mib-files/mib-v2-0/

**Comment by bgermann** [comment]
It is not clear if you can redistribute the file (let alone distribute manipulated versions), so we will not include it.

**Pull request closed without merging**
